name: zynergy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.0.0
  permission_handler: ^11.0.0
  timezone: ^0.9.1
  android_alarm_manager_plus: ^4.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.15
  flutter_statusbarcolor_ns: ^0.6.0
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.10.0"
  google_sign_in: ^6.1.0
  dio: ^5.0.3
  rename: ^3.0.2
  loading_animation_widget: ^1.3.0

flutter_icons:
  android: true
  image_path_android: "assets/icons/icon_launcher.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/icon_launcher.png"
  adaptive_icon_foreground_inset: 8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Black.ttf
          weight: 900
        - asset: assets/fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geist-Thin.ttf
          weight: 100

# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package